# Generated by Django 5.0.1 on 2024-07-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
