# Generated by Django 5.0.1 on 2024-07-23 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0003_remove_guest_phone_number_alter_agent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
