# Generated by Django 5.0.1 on 2024-07-23 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4b50d78-f936-4383-ae01-4f1d69d9447d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
