# Generated by Django 5.0.1 on 2024-07-23 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e1db8be-4424-457c-b62c-4807f98e9cf1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
