# Generated by Django 5.0.1 on 2024-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0007_userprofile_remove_guest_user_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
