# Generated by Django 5.0.1 on 2024-07-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0009_faq_last_updated_alter_faq_question_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='last_updated',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
