# Generated by Django 5.0.1 on 2024-07-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0010_remove_faq_last_updated_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
