# Generated by Django 5.0.1 on 2024-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0012_agentlisting_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlisting',
            name='amenities',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('security', 'Security'), ('cctv', 'CCTV'), ('laundry', 'Laundry'), ('kitchen', 'Kitchen'), ('gym', 'Gym'), ('pool', 'Pool'), ('ac', 'AC'), ('tv', 'TV'), ('furniture', 'Furniture')], default='wifi', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlisting',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='agentlisting',
            name='roomType',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('dormitory', 'Dormitory')], default='single', max_length=50),
        ),
    ]
