# Generated by Django 5.0.1 on 2024-08-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0013_agentlisting_amenities_agentlisting_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlisting',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='amenities',
            field=models.CharField(blank=True, choices=[('wifi', 'WiFi'), ('parking', 'Parking'), ('security', 'Security'), ('cctv', 'CCTV'), ('laundry', 'Laundry'), ('kitchen', 'Kitchen'), ('gym', 'Gym'), ('pool', 'Pool'), ('ac', 'AC'), ('tv', 'TV'), ('furniture', 'Furniture')], default='wifi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='availability',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='hostelName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='roomType',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('dormitory', 'Dormitory')], default='single', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='roomsAvailable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
