# Generated by Django 5.0.1 on 2024-08-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0014_alter_agentlisting_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlisting',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='availability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentlisting',
            name='roomType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
