# Generated by Django 5.0.1 on 2024-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0017_image_agentlisting_images_delete_agentlistingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlisting',
            name='uid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
