# Generated by Django 5.0.1 on 2024-08-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0019_tourrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourrequests',
            name='agent',
        ),
    ]
