# Generated by Django 5.0.1 on 2024-08-10 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0020_remove_tourrequests_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequests',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests', to='Databased.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='requested_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
