# Generated by Django 5.0.1 on 2024-08-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databased', '0021_tourrequests_agent_alter_tourrequests_requested_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourrequests',
            name='agent',
        ),
    ]
